### PR TITLE
fix(#133): Fix item spawner & items

### LINKED ISSUE #133: Fix item spawner & items
- Items not colliding with floor
- Item spawner not triggering
- Item misaligned colliders

### PR DESCRIPTION
**Pull request by Acu1000**
closes #133

### CODE REVIEW

File: Assets/Scripts/ItemSystem/ItemSpawner.cs [hunk 1]
```diff
@@ -84,15 +95,17 @@ void ReInitImage()
 
         private void SetItemIcon()
         {
-            Shader shader = itemInfo?.Icon == null
-                ? Shader.Find("Hidden/InternalErrorShader")
-                : Shader.Find("Universal Render Pipeline/Unlit");
+            if (material) {
```
Comment (PatrykPaluch) [inline Assets/Scripts/ItemSystem/ItemSpawner.cs]: reverse if to avoid nested code:
` if (!material) return;`

File: Assets/Scripts/ItemSystem/ItemSpawner.cs [hunk 2]
```diff
@@ -54,6 +54,17 @@ private void Awake()
...
             ReInitImage();
+            // <TEMP>
+            if (Application.isPlaying)
+            {
+                ItemComponent itemComponent = gameObject.AddComponent<ItemComponent>();
+                itemComponent.Init(new ItemInstance(itemInfo, itemData));
+                Destroy(this);
+                Destroy(GetComponent<MeshRenderer>());
+                Destroy(GetComponent<MeshFilter>());
+                transform.localScale = Vector3.one;
```
Comment (PatrykPaluch) [inline Assets/Scripts/ItemSystem/ItemSpawner.cs:67]: this code should run in build too:

```cs
void OnEnable() 
{
  #if UNITY_EDITOR
  ReInitImage();
  #endif
  if (Application.isPlaying) 
  {
    // code
  }
}
```

**Review by PatrykPaluch — CHANGES_REQUESTED** [review]

**Review by PatrykPaluch — APPROVED** [review]
